version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm cit
      - run: npx @commitlint/cli --from=origin/master --to=HEAD --verbose
  publish_to_npm:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm cit
      - run: npm run semantic-release
  
workflows:
  test:
    jobs:
      - test:
          filters:
            branches:
              ignore: master
      - publish_to_npm:
          filters:
            branches:
              only: master
