version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm cit
  publish_to_npm:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: npm ci
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run: npm version --no-git-tag-version ${CIRCLE_TAG}
      - run: npm publish
  
workflows:
  test:
    jobs:
      - test:
          filters:
            branches:
              ignore: master
      - publish_to_npm:
          filters:
            branches:
              only: master
